Trading API: Adds TradingClient and Create Order Route
alpacahq/alpaca-py pull request #72
Opened 2022-05-23 13:49 UTC by haxdds

2022-05-24 19:03 UTC, drew887 requested changes

2022-05-25 19:05 UTC, haxdds commented on alpaca/trading/client.py
> +        """ """
added missing docstrings is #73

2022-05-25 19:06 UTC, haxdds commented on alpaca/trading/client.py
> +class TradingClient(RESTClient):
Added missing docstrings in #73

2022-05-25 19:07 UTC, haxdds commented on alpaca/trading/client.py
> +        """ """
Added missing docstrings in #73

2022-05-26 16:50 UTC, merged